# https://circleci.com/docs/2.0/language-javascript/
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm-install
          command: npm install
      - run:
          name: npm-build
          command: npm run build
          no_output_timeout: 10m
      - run:
          name: npm-clean
          command: npm run clean
          no_output_timeout: 10m
      - run:
          name: npm-test
          command: npm run test
          no_output_timeout: 10m
      - run:
          name: npm-webpack:prod
          command: npm run webpack:prod
          no_output_timeout: 10m
      - run:
          name: npm-clean
          command: npm run clean
          no_output_timeout: 10m
